# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('course_number', models.CharField(max_length=3)),
                ('credit_hours', models.IntegerField()),
                ('also_offered_as', models.ManyToManyField(related_name='_course_also_offered_as_+', to='student_assistance_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('abbr_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required_hours', models.IntegerField()),
                ('required_classes', models.IntegerField()),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Department')),
                ('requirements', models.ManyToManyField(to='student_assistance_system.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('enrolled', models.IntegerField()),
                ('professor', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minors', models.ManyToManyField(to='student_assistance_system.RequirementSet')),
            ],
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='student_assistance_system.RequirementSet')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.RequirementSet')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.User')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='sections',
            field=models.ManyToManyField(to='student_assistance_system.Section'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.User'),
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(to='student_assistance_system.Course'),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Course'),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.User'),
        ),
    ]
