# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_assistance_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minors', models.ManyToManyField(to='student_assistance_system.RequirementSet')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='minors',
        ),
        migrations.AlterField(
            model_name='completedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Profile'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Profile'),
        ),
        migrations.AlterField(
            model_name='usermajor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
