# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0002_auto_20161026_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_times',
            field=models.ManyToManyField(to='student_assistance_system.MeetingTime'),
        ),
    ]
