# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0002_auto_20161026_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='May 2017', max_length=50),
            preserve_default=False,
        ),
    ]
