# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0003_auto_20161027_2027'),
        ('student_assistance_system', '0003_profile_year'),
    ]

    operations = [
    ]
