# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0004_merge_20161027_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMeetingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.MeetingTime')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_assistance_system.Section')),
            ],
        ),
    ]
