# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0005_sectionmeetingtimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmeetingtimes',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='sectionmeetingtimes',
            name='section',
        ),
        migrations.DeleteModel(
            name='SectionMeetingTimes',
        ),
    ]
