# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0007_auto_20161110_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='query',
            field=models.TextField(),
        ),
    ]
