# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_assistance_system', '0008_auto_20161111_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=4),
        ),
    ]
